ALTER TABLE orders
ADD COLUMN accepted_at TIMESTAMP NULL,
ADD COLUMN prepared_at TIMESTAMP NULL,
ADD COLUMN dispatched_at TIMESTAMP NULL,
ADD COLUMN delivered_at TIMESTAMP NULL,
ADD COLUMN cancelled_at TIMESTAMP NULL;