ALTER TABLE orders
ADD COLUMN accepted_at TIMESTAMP NULL,
ADD COLUMN preparing_at TIMESTAMP NULL,
ADD COLUMN ready_at TIMESTAMP NULL,
ADD COLUMN dispatched_at TIMESTAMP NULL,
ADD COLUMN delivered_at TIMESTAMP NULL,
ADD COLUMN cancelled_at TIMESTAMP NULL;